name: run test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [stable, 2.17.6]
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: cd test && dart pub get
      - name: Run tests
        run: |
          cd github_tests && dart run test